plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/gnemo/Desktop/Personal Project/gnmeo个人设计网页中文版/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]